name: Deploy to GitHub Pages

on:
  push:
    branches: "main" # Asegúrate de que este sea el nombre de tu rama principal

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Usamos la versión 22 para evitar avisos de depreciación
          # Eliminamos la línea de 'cache' si existía, que es lo que causaba el error del lock file

      - name: Install dependencies
        run: npm install # Esto generará el lock file en el corredor de GitHub automáticamente

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite genera la web en la carpeta dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
